defined RamdomEngine class
hnccbits/passgen-cpp pull request #6
Opened 2021-05-11 06:00 UTC by DivasGupta7

2021-05-11 10:27 UTC, anjanik012 commented
This is technically a declaration and not definition.

2021-05-11 10:31 UTC, anjanik012 requested changes

2021-05-11 10:31 UTC, anjanik012 commented on src/engine.h
> +#include <stdint.h>
There should be `cstdint` header file or integer definitions should work without including this. Test this out

2021-05-11 10:31 UTC, anjanik012 commented on src/engine.h
>  class RandomEngine {
Please reformat code. Indent spaces properly.

2021-05-11 10:31 UTC, anjanik012 commented on src/engine.h
> +    RandomEngine(uint8_t l);
constructors with exactly one argument should be marked `explicit`

2021-05-11 10:31 UTC, anjanik012 commented on src/engine.h
> +    int getLength();
return type should be `uint8_t`

2021-05-11 10:32 UTC, anjanik012 commented
Also, where are definitions, are you working on it?

2021-05-11 14:25 UTC, DivasGupta7 commented
> Also, where are definitions, are you working on it?

yes sir,we are working on it in engine.cpp file

2021-05-11 16:27 UTC, anjanik012 requested changes

2021-05-11 16:27 UTC, anjanik012 commented on src/engine.h
> +         int getLength();
Return type is incorrect.

2021-05-12 07:07 UTC, anjanik012 commented on src/engine.h
> +         u_int8_t getLength();
still incorrect, correct is `uint8_t`. Look what you commit!!

2021-05-12 08:53 UTC, anjanik012 requested changes

2021-05-12 08:53 UTC, anjanik012 commented on src/engine.h
> +         uint8_t length=0;
This is not the way to initialize variables, all class members must be initialized via constructors

2021-05-12 09:41 UTC, anjanik012 commented
There are a few more changes that I would like to have but never mind. Merging.

2021-05-12 09:42 UTC, merged